[package]
name = "fama"
version = "0.1.3"
edition = "2021"
license = "MIT"
description = "Pipeline Manager"
repository = "https://github.com/shiftrightonce/fama"
rust-version = "1.70"
keywords = ["webdev", "web", "event", "pipeline", "pipeline-pattern"]
categories = ["asynchronous", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"

[dev-dependencies]
tokio = { version = "1.28.2", features = ["full"] }
uuid = { version = "1.3.4", features = ["v4"] }
